apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dulanji
  name: dulanji
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: dulanji
status:
  loadBalancer: {}